language: node_js
matrix:
  include:
  - node_js:
    - '10'
    - '8'
    - '6'
    env:
    - CAN_DEPLOY=true
notifications:
  email:
    on_success: never
before_install:
  - npm -g install npm@4
script: npm run ci
